name: FastAPI CD Pipeline

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Build and Run Docker container
        run: |
          sudo docker build -t fastapi-app .
          sudo docker rm -f fastapi-app-container || true
          sudo docker run -d -p 8000:8000 --name fastapi-app-container fastapi-app