name: FastAPI CD Pipeline

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t fastapi-app .
    - name: Push to Docker Hub
      run: docker push franknonso/fastapi-app:latest

  deploy:
    if: github.event.pull_request.merged == true

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull franknonso/fastapi-app:latest
    - name: Delete old Docker container
      run: sudo docker rm -f fastapi-app-container || true
    - name: Run Docker container
      run: sudo docker run -d -p 8080:8080 --name fastapi-app-container franknonso/fastapi-app

