name: FastAPI CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Install your project dependencies
          pip install pytest # Install pytest

      - name: Run tests
        run: pytest

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-reports
          retention-days: 7
